const config = {
  title: "Terra's Dev Blog",
  description: "Hello World",
  company: "(주)네오사피엔스",
  companyURL: "https://company.typecast.ai/ko/",
  position: "프론트엔드 개발자",
  siteURL: "https://next-blog-beige-alpha.vercel.app/",
  language: "ko",
  image: "https://next-blog-beige-alpha.vercel.app/images/hero.jpg",
  favicon: "https://next-blog-beige-alpha.vercel.app/favicon.ico",
  author: "dev2820",
  name: "양기조",
  nickname: "Terra",
  email: "second28200@gmail.com",
  cv: "https://next-blog-beige-alpha.vercel.app/about",
  country: "Korea",
  region: "Seoul",
  profile: "https://avatars.githubusercontent.com/u/40891497?v=4",
  githubId: "dev2820",
  githubURL: "https://github.com/dev2820",
  linkedinId: "기조-양-866826260",
  linkedinURL: "https://www.linkedin.com/in/기조-양-866826260",
};

export default config;
